config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  resources :users, :except =>[ :edit,:create ] 
  resources :questions do
    resources :answers , :except =>[ :index,:show,:new ]
  end
   root 'welcome#index'
   get  'dashboard'   => 'questions#index', as: :user_root
   post 'create_user' => 'users#create_me'
  

end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many   :answers,dependent: :destroy
  belongs_to :user
  validates  :title,presence: true
  enum category: { cs: "cs" , ee: "ee" }

  def self.get_question_answers_count
  	joins("LEFT OUTER JOIN answers on questions.id=answers.question_id").group("questions.id").select("questions.*, count(answers.id) as total_answers")
  end
  
  def self.search_questions_with_title( search_title )
  	where("title LIKE ?","%#{search_title}%")
  end

  def self.filter( options )
    @questions = Question.all.get_question_answers_count
    where_hash = Hash.new
    where_hash[:title] = options[:search] if options[:search].present?
    where_hash[:category] = options[:category] if options[:category].present?
    @questions = @questions.where(where_hash)
    @questions = @questions.order("#{options[:sort_by]} #{options[:sorting_order]}") if options[:sort_by].present? && options[:sorting_order].present?
    @questions = @questions.having("total_answers=?",options[:answer_count])
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  skip_authorization_check only: :index
  load_and_authorize_resource
  
  # GET /questions
  def index
    options = Hash.new
    options[:search]       = params[:search]   
    options[:sort_by]      = params[:sort_by]  
    options[:category]     = params[:category]
    options[:sorting_order]= params[:sorting_order] 
    options[:answer_count] = params[:answer_count].to_i
    @questions = @questions.filter(options)
    respond_to do |format|
      format.html
    end
  end

  # GET /questions/1
  def show
    @answers = @question.answers
    respond_to do |format|
      format.html
    end
  end
  # GET /questions/new
  def new
    respond_to do |format|
      format.html
    end
  end

  # GET /questions/1/edit
  def edit
    respond_to do |format|
      format.html
    end
  end

  # POST /questions
  def create
    @question.user_id = current_user.id
    respond_to do |format|
      if @question.save
        flash[:success] = t("questions.create.success")
        format.html { redirect_to @question }
      else
        flash[:danger] = t("questions.create.error")
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /questions/1
  def update
    respond_to do |format|
      if @question.update(question_params)
        flash[:success] = t("questions.update.success")
        format.html { redirect_to @question }
      else
        flash[:danger] = t("questions.update.error")
        format.html { render :edit }
      end
    end
  end

  # DELETE /questions/1
  def destroy
    @question.destroy
    respond_to do |format|
      if @question.destroyed?
        if current_user.id != @question.user_id && current_user.admin?
          @user = @question.user
          ExampleMailer.sample_email(@user).deliver
        end
        flash[:success] = t("questions.destroy.success")
        format.html { redirect_to user_root_path }
      else
        flash[:danger] = t("questions.destroy.error")
        format.html { redirect_to user_root_path }
      end
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :content, :category)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
      <%= f.label :title, class: 'required'%><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :Description %><br>
      <%= f.text_area :content, rows:"5", cols:"30"%>
    </div>
    <div class="field" >
     <%= f.select :category, collection: Question.categories.keys.to_a %>
    </div>

    <div class="actions">
      <%= f.submit "Post", class:"btn btn-primary" %>
    </div>
<% end %>

app/views/questions/_question.html.erb
<tr>
  <td> <strong><%= question.title %></strong> </td>
  <td> <%= question.content %> </td>
  <td> <%= link_to 'Show', question %> </td>
</tr>

app/views/questions/_question_list.html.erb
<tr>
  <td><strong><%= question.title %></strong></td>
  <td><%= link_to 'Show', question %></td>
  <% if user_signed_in? && can?(:edit, question)%>
    <td><%= link_to 'Edit', edit_question_path(question) %></td>
  <% else %>
    <td><%= "Not Allowed"%></td>
  <% end %>
  <% if user_signed_in? && can?(:destroy, question) %>
    <td><%= link_to 'Delete', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <% else %>
    <td><%= "Not Allowed"%></td>
  <% end %>
  <td><%= question.category %></td>
  <td><%= question.total_answers%></td>
</tr>

app/views/questions/_search_to_form.html.erb
<div class="row" id="advanced-search-form" style="margin-left: 12px; margin-bottom: 20px" >
<%= form_tag(questions_path, :method => "get", id: "advanced-search-display") do %>
   <%= label_tag "Sort By"%> 
    <%= select_tag(:sort_by, options_for_select([["",""],["creation","created_at "],["title","title "]]), class:"select") %> &nbsp
 	<%= label_tag "Category"%>
    <%= select_tag(:category, options_for_select([["",""],["cs","cs"],["ee","ee"]]), class:"select") %> &nbsp
  <%= label_tag "Sorting order"%>
  <%= select_tag(:sorting_order, options_for_select([["",""],["Ascending","asc"],["Descending","desc"]]), class:"select") %> &nbsp 

    <%= label_tag "Answers Count"%>
	<%= number_field_tag :answer_count, nil, min: 0, step: 1 %> &nbsp
	 <%= label_tag "Title"%>
	<%= text_field_tag :search, params[:search], placeholder: "Search question by title" %> 
	<div id="search-button" style="display: inline; margin-left: 37px;">
     <%= submit_tag "Search", :name => nil, class:"btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/questions/edit.html.erb
<% provide(:title,"update question")%>
<h1>Edit Question</h1>
<div class="row" style="margin-left: 5px;">
<%= render 'form' %>
</div>

<!--<%= link_to 'Show', @question %>-->
<!-- 
<%= link_to 'Back', questions_path %>-->

app/views/questions/index.html.erb
<div class="row">
  <%= render partial:"search_to_form"%>
  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
</div>
<div class="row" style="margin-bottom: 15px">
  <div class="col-md-2"> 
    <h2>Questions</h2>
  </div>
  <div class="col-md-8">
  </div>
  <div class="col-md-2">
    <% if user_signed_in? %>
      <div id="button-margin">
        <%= button_to 'Ask Question', new_question_path(@question), method: :get, :class => "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th colspan="1">Title</th>
      <th colspan="3">Actions</th>
      <th> Category </th>
      <th> Total Answers </th> 
    </tr>
  </thead>
  <tbody>
    
    <% @questions.each do |question| %>
      <%= render partial: 'question_list', locals: { question: question } %>
    <% end %>
  </tbody>
</table>
<br/>


 <script type="text/javascript">
 </script>

app/views/questions/new.html.erb
<% provide(:title,"create question")%>
<h1>Post Question</h1>
<div class="row" style="margin-left: 5px;">
  <%= render 'form' %>
</div>

app/views/questions/show.html.erb
    <div class="whole-question-detail" style="margin-left: 15px;">

      <div class="row">
        <div class="question-title">
          <h2><%= @question.title %></h2>
        </div>

      </div>

      <div class="row">
        <div class="question-description">
          <%= @question.content %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
          <div class="question-buttons" class="btn-group" style="margin-left: -14px;">
            <% if can? :edit, @question %>
              <%= button_to 'Edit', edit_question_path(@question), method: :get, :class=> "btn btn-info" %>
            <% end %>
            <% if can? :destroy, @question %>
              <%= button_to 'Delete', question_path(@question), method: :delete, data: { confirm: 'Are you sure?' }, :class=> "btn btn-danger" %>
            <% end %>  
          </div>
        </div>
        <div class="col-md-6">
        </div>
        <div class="col-md-2">
            <p> Posted By:<strong><%= @question.user.name %></strong></p>
            <strong><%= @question.created_at %></strong>
        </div>
      
      <div class="row" id="answer-count-margin">
        <h1 id="get_answer_count"><%= pluralize(@answers.count, "Answer") %></h1>  
      </div>
      <div id="ajax-answer-call">
        <%= render @answers %>
      </div>

      <div class="row" >
        <%= render partial: 'answers/form', locals:{answer: @question.answers.build}%>
      </div>
    </div>