config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  resources :users, :except =>[ :edit,:create ] 
  resources :questions do
    resources :answers , :except =>[ :index,:show,:new ]
  end
   root 'welcome#index'
   get  'dashboard'   => 'questions#index', as: :user_root
   post 'create_user' => 'users#create_me'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions,dependent: :destroy
  has_many :answers,dependent: :destroy
  devise   :database_authenticatable,:registerable,
           :recoverable,:rememberable,:trackable,:validatable,:confirmable
  before_save { self.email==email.downcase }
  default_scope -> { order(created_at: :desc) }
  enum role: { user:1 , admin:0 }

  def admin?
    role == "admin"
  end

  
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]
  # GET /resource/sign_up
  # def new
  #   super
  # end
  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation,:role)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end


 
  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end
  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user_data, only: :create_me
  load_and_authorize_resource

  # GET /users
  def index
    respond_to do |format|
      format.html
    end
  end

  # GET /users/1
  def show
    @questions = @user.questions
    respond_to do |format|
      format.html
    end
  end
  # GET /users/new
  def new
    respond_to do |format|
      format.html
    end
  end
  # POST /users
  def create_me
    respond_to do |format|
      if @user.save
        flash[:success] = t("users.create_me.success")
        format.html { redirect_to users_path }
      else
        flash[:danger] = t("users.create_me.error")
        format.html { render :new }
      end
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    respond_to do |format|
      if@user.destroyed?
        flash[:success] = t("users.destroy.success")
        format.html { redirect_to users_url }
      else
        flash[:danger] = t("users.destroy.error")
        format.html {redirect_to users_url}
      end
    end
  end

  private
    def load_user_data
      @user = User.new(user_params)
      unless @user.admin?
        @user[:role] = 1
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:id, :name, :email, :password, :role)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user, url: create_user_path ) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name  %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email,class: 'required'%><br>
    <%= f.text_field :email %>
  </div>
  <div class="field" >
    <%= f.label :password,class: 'required' %><br>
    <%= f.password_field(:password) %>
  </div>
  <div class="field" >
   <%= f.select :role, collection: User.roles.keys.to_a %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-6">
    <h2>USERS WITH FOLLOWING EMAILS</h2>
  </div>
  <div class="col-md-4">
  </div>
  <div class="col-md-2" style="margin-top: 18px;">
    <%= button_to 'Create User', new_user_path, method: :get, :class=> "btn btn-info" %>
  </div>
</div>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Email</th>
      <th>Show </th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <% if user.id != current_user.id %>
          <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
          <td> Not Allowed</td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br/>

app/views/users/new.html.erb
<% provide(:title,"create user")%>
<h1>Login</h1>
<div class="row" style="margin-left: 5px;">
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<% provide(:title,@user.name)%>
<div class="row">
  <div class="col-md-2">
    <h2>
      <%= @user.name %>
    </h2>
  </div>
</div>
<div class="row">
  <% if @questions.any? %>
    <h1> <%= pluralize(@questions.count, "Question") %></h1>
    <table class="table table-bordered" style="margin-left: 15px;">
      <thead>
        <tr>
          <th>Title</th>
          <th>Content</th>
          <th>Details</th>
        </tr>
      </thead>
      <tbody>
        <%= render @questions%>
      </tbody>
    </table>
  <% end %>
</div>


            