config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  resources :users, :except =>[ :edit,:create ] 
  resources :questions do
    resources :answers , :except =>[ :index,:show,:new ]
  end
   root 'welcome#index'
   get  'dashboard'   => 'questions#index', as: :user_root
   post 'create_user' => 'users#create_me'
  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  validates  :content,presence: true

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user_login, only: :create
  load_and_authorize_resource :question 
  load_and_authorize_resource :answer, through: :question

   # Get /questions/:question_id/answer/id/edit
  def edit
    respond_to do |format|
      format.js
    end
  end

  # Post /questions/:question_id/answers
  def create
    updated_params = answer_params.merge(user_id: current_user.id)
    @answers  = @question.answers
    @answer   = @answers.build(updated_params)
    respond_to do |format|
      if @answer.save
        flash.now[:success] = t("answers.create.success") 
        format.js
      else
        flash.now[:success] = t("answers.create.error")
        format.js
      end
    end
  end

  # PATCH/PUT questions/:question_id/answers/id
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        flash.now[:success] = t("answers.update.success")
        format.js
      else
        flash.now[:success] = t("answers.update.error")
        format.js
      end
    end
  end

  # DELETE /questions/:question_id/answers/id
  def destroy
    @answer.destroy
    respond_to do |format|
      if @answer.destroyed?
        flash.now[:success] = t("answers.destroy.success")
        format.js
      else
        flash.now[:success] = t("answers.destroy.error")
        format.js
      end  
    end
  end

  def authenticate_user_login
    if current_user.blank?
      respond_to do |format|
        flash[:danger] = t("answers.authenticate_user_login.error")
        format.html{redirect_to new_user_session_path( page_referrer: request.referrer )}
      end
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:content)
    end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<div id="answer">
	<div class="row">
	  <div id="answer-content-<%=answer.id%>" style="margin-bottom: 15px;">
	    <%= answer.content%>
      </div>
    </div>
	<div class="row">
      <div class="col-md-2">
		<div id="posted-by-details-<%=answer.id%>" style="margin-left: -14px;">
		  <p>Posted By:<strong><%= answer.user.name%></strong></p>
		</div>
	  </div>
	  <div class="col-md-9">
	  </div>
	  <div class="col-md-1" style="display: flex">
		<% if can? :edit,answer %>
		  <div id="edit-link-<%=answer.id%>" style="margin-right: 2px;">
		      <%= link_to 'edit',edit_question_answer_path(@question,answer), class:"btn btn-info", remote:true %>
		  </div>
		<% end %>
		<% if can? :destroy,answer %>
		  <div id="delete-link-<%=answer.id%>">
		    <%= link_to 'delete' , [ @question,answer ], method: :delete,data: { confirm: 'Are you sure?' }, class:"btn btn-danger", remote:true %>
	      </div>
		<% end %>
	  </div>	
	</div>
</div>

app/views/answers/_form.html.erb
<% @answer ||= local_assigns[:answer] %>
<%= form_for([@question,@answer], remote:current_user) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>
      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :content , 'Answer Description', class: 'required'%><br>
    <div id="get-content">
      <%= f.text_area :content, rows:"6",cols:"35",:required => 'required' %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit(class: "btn btn-primary") %>
  </div>
<% end %>

app/views/answers/create.js.erb
$("#ajax-answer-call").append("<%= escape_javascript render partial: 'answer', locals: { answer: @answer }%>");
$("#answer_content").val('')
alert("<%= flash.now[:success]%>");
$("#get_answer_count").text('<%= pluralize(@answers.count, "Answer")%>')

app/views/answers/destroy.js.erb
$("#answer-content-<%= @answer.id%>").remove();
$("#edit-link-<%= @answer.id%>").remove();
$("#delete-link-<%= @answer.id%>").remove();
$("#posted-by-details-<%=@answer.id%>").remove();
alert("<%= flash.now[:success]%>");
$("#get_answer_count").text('<%= pluralize(@question.answers.count, "Answer")%>')

app/views/answers/edit.html.erb
<% provide(:title,"edit answer")%>
<h1>Editing Answer</h1>
<div class="row" >
<%= render 'form' %>
</div>

app/views/answers/edit.js.erb
$("#answer-content-<%= @answer.id %>").html("<%= escape_javascript render partial:'answers/form' %>");
$("#edit-link-<%= @answer.id%>").hide();

app/views/answers/update.js.erb
$("#answer-content-<%= @answer.id %>").html("<%= escape_javascript @answer.content %>");
$("#edit-link-<%= @answer.id%>").show();