config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  resources :users, :except =>[ :edit,:create ] 
  resources :questions do
    resources :answers , :except =>[ :index,:show,:new ]
  end
   root 'welcome#index'
   get  'dashboard'   => 'questions#index', as: :user_root
   post 'create_user' => 'users#create_me'
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Stack Overflow sample application</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Sample Project", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        	<li><%= link_to "Home", questions_path %></li>
          <% if can? :index, User %>
          <li><%= link_to "Users", users_path %></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
        	<li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/header' %> 
  <%= render 'layouts/shim'%>
</head>
<body>
	<div class="container">
		<div id="flash-messages">
			<%= render 'shared/flash_messages' if !flash.empty? %>
		</div>
        <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
</body>
</html>